#!pyobjects

Pkg.installed("emacs24")
Pkg.installed("vim")
Pkg.installed("salt-common")
Pkg.installed("git")
Pkg.installed("cython")
Pkg.installed("libxml2-dev")
Pkg.installed("libxslt1-dev")
Pkg.installed("libmysqlclient-dev")
Pkg.installed("python-dev")
Pkg.installed("python-virtualenv")
Pkg.installed("virtualenvwrapper")
Pkg.installed("fabric")
Pkg.installed("libpq-dev")
Pkg.installed("libgdal-dev")
